# Generated by Django 3.0.5 on 2020-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
