# Generated by Django 3.0.5 on 2020-04-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
